#!/bin/bash

HERE="`dirname "$0"`"
cd "$HERE"

sh Prepare
MODULES=( Tools MuiKit Mover )
for MODULE in "${MODULES[@]}"; do
	(cd "$MODULE" && git checkout master && git pull origin master) || exit 1
done
